### PR TITLE
Treat unit types as erased in constructors

### PR DESCRIPTION
**Pull request by Z-snails**
# Description

Credit to @andrevidela for the suggestion

This doesn't pass tests on my PC, maybe somehow it will in CI?

## Should this change go in the CHANGELOG?

- [x] If this is a fix, user-facing change, a compiler change, or a new paper
      implementation, I have updated `CHANGELOG.md` (and potentially also
      `CONTRIBUTORS.md`).

### CODE REVIEW

**Comment by dunhamsteve** [comment]
chez033, chez035, and building prelude (self-hosted) are failing. Not sure exactly what's going on here, but it seems to fail with `No Clauses` (in casebuilder) when incremental codegen is turned on. 

One option is CompileExpr.idr:802 where `eraseArgs` is not called for holes, but I'm not sure that applies to the test case.

The other possibility is Inline.idr.  Lines 585 and 549 consult `incrementalCGs` and behave differently from normal compiles.

**Comment by Z-snails** [comment]
I think I've figured out the problem, and that is chez scheme evaluates zero-argument functions before they are called - but this is only a problem in incremental mode, because otherwise the function doesn't even get compiled (in this case it's one of the uninhabited instances)

I can fix this by disabling eager evaluation of constants on the incremental backend. Let me know if you can think of a better way to fix this

**Comment by Z-snails** [comment]
Turns out this bug is also present on idris2 main, even without incremental mode:

```idris
bad : (0 _ : Z = S Z) -> Void
bad _ impossible

data BadPrf = Ok | No (Z = S Z)

Show BadPrf where
    show Ok = "Ok"
    show (No prf) = absurd $ bad prf

main : IO ()
main = printLn Ok
```

**Comment by dunhamsteve** [comment]
I was curious what effect this had on performance, so I ran `time idris2 --build idris2api.ipkg` with a clean build directory using an idris built with this branch (with my patches) and also with the main branch of idris. (M1 mac, racket chez at the racket-v8.9 tag.)

The times for the main branch were 1:56.53 and 1:56.57, the times for this branch were 1:55.48 and 1:55.59.  So it looks like about a 1% reduction in time.

**Pull request merged**
