### PR TITLE
Change semantics of lines and unlines function to match Haskell and other languages

### PR DESCRIPTION
**Pull request by stepancheg**
## Add newline in `unlines` function (first commit)

There are several reasons to do that:
* a line in a text file is something which ends with newline,
  and the last line is not special
* `unlines []` should be different from `unlines [""]`
* `unlines (a ++ b) = unlines a ++ unlines b`
* Haskell does it

## `lines ""` should be `[]` list, not `[""]` (second commit)

I suspect this is what most users expect. And this is what virtually all other implementations do.

### CODE REVIEW

**Comment by mattpolzin** [comment]
Doesn't this break the following equality though?
```idris
unlines . lines = id 
```

I feel it's important that lines and unlines are inverse operations.

**Comment by stepancheg** [comment]
> Doesn't this break the following equality though?

It does.

```
lines "" = [""]
```

Which also looks incorrect to me: empty files contains zero lines, not one.

**Comment by stepancheg** [comment]
Another issue with `lines`:

```
lines "a\r\nb" = ["a", "", "b"]
```

**Comment by mattpolzin** [comment]
I think my point serves a different conclusion for me, though: files without trailing new lines are not invalid and I would want to be able to lines & unlines them without introducing a newline at the end that wasn’t there to begin with.

**Comment by stepancheg** [comment]
> files without trailing new lines are not invalid

Yes they aren't invalid, and I'm not going to change that.

But file like: `"a\n"` contains one line, not two, right?

**Comment by stepancheg** [comment]
Also, just in case, all programming languages I have found:
* Haskell
* Python
* Rust
* Java `BufferedReader.readLine`
* C `getline` function
Return empty list on empty input. I don't see a compelling reason why Idris should be different.

Argument about strict inverse is not convincing for me:
* `lines` and `unlines` function is a practical function to work with text file, not an abstract function like `filter` or `map`
* `lines` and `unlines` are already not inverse of each other, because `lines` treats `\r` and `\n` the same, as newline, and on `unlines` it joins lines with `\n`

**Comment by stepancheg** [comment]
Added second commit to PR to patch `lines` function too.

**Comment by edwinb** [comment]
I'm inclined to agree that the semantics should match what other languages do, despite the functions no longer being inverses, especially given that they weren't inverses anyway. I'm not sure what's up with the CI, though.

The added tests here also illustrate that we really need to think about property testing/unit testing for the libraries. Golden tests for libraries are annoyingly expensive, especially given the Chez start up time. But, that's a different issue.

**Comment by gallais** [comment]
It's annoying when putting together complex messages that that `unlines [unlines xs]`
is not the same as `unlines xs` but I guess that's just more motivation to switch to
the pretty printing library and use `vcat` instead.

**Comment by stepancheg** [comment]
> `unlines [unlines xs]` is not the same as `unlines xs`

I think of it this way: there are logically two types: "line" and "text", although both represented by `String`.

* `unlines` accept "lines" and returns "text"
* `lines` accept "text" and returns "lines"

So the equivalent operation should be:

```
unlines $ lines $ unlines xs
```

**Comment by stefan-hoeck** [comment]
Just a quick note: This PR (which I missed while it was not yet merged) broke half of my libraries since the type of `unlines` was changed.  While the fix was trivial in this case, I'd like to stress that breaking changes really should not be introduced into the standard libs / compiler without a proper proposal in the issue tracker. At the very least, the name of the PR should be prefixed with `[ breaking ]`.

**Pull request merged**
