### PR TITLE
add EitherT transformer

### PR DESCRIPTION
**Pull request by MarcelineVQ**
add EitherT transformer
add Foldable/Traversable implementations for Either

Filling in the missing zoo as needed.

### CODE REVIEW

**Comment by gallais** [comment]
Don't forget to add the new module to the corresponding `ipkg` file.

The build failure seems unrelated to your changes. Looks like my tests for the
logging behaviour are pretty annoying because they reference internal name. I'll
try to add a bit of `sed` magic to clean up the output & hopefully they won't
break quite as many new PRs!

**Comment by MarcelineVQ** [comment]
Oh yes how silly of me considering I've done just that on other projects

**Comment by clayrat** [comment]
> The build failure seems unrelated to your changes. Looks like my tests for the
> logging behaviour are pretty annoying because they reference internal name. I'll
> try to add a bit of `sed` magic to clean up the output & hopefully they won't
> break quite as many new PRs!

Yeah, I also had to manually update `basic044` for #579

**Comment by gallais** [comment]
Hoping #593 will be sufficiently portable to not fail on mac OS & windows.
A more long term solution would be to have a flag telling the printer not to
display internal names. But printing is pure atm I believe so that'd be quite
a big change.

**Pull request merged**
