### PR TITLE
Use C idris2_time for all C-based backends

### PR DESCRIPTION
**Pull request by stepancheg**

### CODE REVIEW

**Comment by gallais** [comment]
I'm not sure what the justification for this is?
All the other time variants are kept:

```
(define (blodwen-clock-time-utc) (current-time 'time-utc))
(define (blodwen-clock-time-monotonic) (current-time 'time-monotonic))
(define (blodwen-clock-time-duration) (current-time 'time-duration))
(define (blodwen-clock-time-process) (current-time 'time-process))
(define (blodwen-clock-time-thread) (current-time 'time-thread))
(define (blodwen-clock-time-gccpu) (current-time 'time-collector-cpu))
(define (blodwen-clock-time-gcreal) (current-time 'time-collector-real))
```

and this adds FFI indirection for all of the scheme backends AFAICT.
You'd hope that potentially blocking on `time` is not problematic but
still why would you if you don't need to?

**Comment by stepancheg** [comment]
> I'm not sure what the justification for this is?

* less code
* the same implementation (and thus behavior) in all C-based backends

> this adds FFI indirection for all of the scheme backends AFAICT

There's FFI somewhere anyway: either FFI is exposed directly to Idris, or hidden somewhere in Scheme standard library. The number of FFI calls is the same.

> All the other time variants are kept:

I think they should also be replaced with C backend calls.

> You'd hope that potentially blocking on time is not problematic but still why would you if you don't need to?

I didn't get it: `time` is non-blocking call (moreover, on Linux with VDSO it is usually even not a syscall).

**Comment by gallais** [comment]
Chez does weird things with ffi calls it does not trust (i.e. all the ones that
are not provided by the language itself like `time` is): https://github.com/idris-lang/Idris2/wiki/Networking-primitives

**Comment by stepancheg** [comment]
Well, Chez `time` call seems to be not different from the call proposed in this PR:

[snippet 1: $clock-gettime](https://github.com/cisco/ChezScheme/blob/5fac773af3259246f91766d3da50d27341b66358/s/date.ss#L84-L86)
```scheme
  (define $clock-gettime ; clock_id -> tspair
    (foreign-procedure "(cs)clock_gettime"
      (integer-32)
      scheme-object))
```

[snippet 2: S_clock_gettime](https://github.com/cisco/ChezScheme/blob/5fac773af3259246f91766d3da50d27341b66358/c/stats.c#L312)

`time` function is not blocking, and blocking calls are different, they should do something like (not sure exactly)
* need to be annotated with `C__collect_safe`
* cannot accept any GC parameters (unless they manually unlock/lock threads)

So this PR of mine #1620 seems to be incorrect and need to be reverted to reworked — native `system` function [unlocks/locks the threads](https://github.com/cisco/ChezScheme/blob/5fac773af3259246f91766d3da50d27341b66358/c/prim5.c#L603-L607). However, I'm not sure that Chez does it correctly. I tested it with this program:

```
(begin
  (fork-thread (lambda ()
    (display "in thr\n")
    (system "sleep 1")
    (display "in thr done\n")
  ))
  (display "outer\n")
  (system "sleep 1")
  (display "outer done\n")
  (system "sleep 1")
  (display "outer done done\n")
)
```

It executes in 3 seconds (not 2), and prints:

```
outer
in thr
# 1 second delay
outer done
# 1 second delay
in thr done
# 1 second delay
outer done done
```

So `system` calls are not executed in parallel in different threads.

Anyway, this is not the hill to die on, just thought some unification would be beneficial to stdlib. If you think this PR should be closed, so be it.

Thank you for the pointers to docs! I learned something about Chez today.

**Comment by edwinb** [comment]
We do need to be a bit careful with Chez and C calls, although in general I prefer to use the C version where it's available because we won't necessarily use Scheme forever. I think this one is okay.

**Pull request merged**
