### PR TITLE
[ new ] Tab completion

### PR DESCRIPTION
**Pull request by stefan-hoeck**
As requested in #1295. The idea is very similar to what [stack does](https://docs.haskellstack.org/en/stable/shell_autocompletion/).

Edit: Somebody please fix the markdown in `INSTALL.md`. Lessons learned: Don't touch anything, or the linter starts drooling :-)
Edit2: "Somebody" turned out to be me...

### CODE REVIEW

**Comment by gallais** [comment]
There seems to be a bug when you only have `idris2 `:

```shell
$ idris2 
Display all 260 possibilities? (y or n)
-?                        chez                      directory.                GAMBIT_GSC                import                    mode                      port                      string
(0                        chez)                     Disables                  GAMBIT_GSC_BACKEND        in                        mode;                     --prefix                  supported
0.3.0-656988f1c           Chez                      display                   GAMBIT_GSI                
(...)
```

As soon as you double tab on `idris2 -` instead you only get the options.

**Comment by stefan-hoeck** [comment]
This should be fixed not. TAB completion is not super fast, since Idris2 startup time is around 0.5 s (on my system) even when invoking `idris2 --version`, but we will see if this is an issue for the fast typers (haha) in the community. There's still the alternative of having a much smaller standalone program, but this will not get the full Idris2 environment (for instance to list additional codegens) and maintenance would be harder.

**Comment by stefan-hoeck** [comment]
Rebased and using `knownTopics` now for log completion. But now a question: Is it correct, that the loglevel is specified using the following syntax:

```sh
> idris2 --log unify.binder:5
```

Should we therefore support the completion of the `:5` part as well?

**Comment by gallais** [comment]
Note that any prefix "m.n" of an existing "m.n.p.q" topic is a valid topic too.
Not sure we handle that properly at the moment.

> Should we therefore support the completion of the :5 part as well?

I think it'd be annoying to explicitly list the levels available for each topic.

**Comment by stefan-hoeck** [comment]
Should work now.

**Pull request merged**
