### PR TITLE
[ performance ] Memoise toplevel constants

### PR DESCRIPTION
**Pull request by stefan-hoeck**
As discussed in #1869, this PR converts zero argument toplevel lamdas to lazily evaluated, memoised constants on scheme backends. Now that we have `blodwen-lazy` in the scheme support files, we can also easily start experimenting with memoising `Lazy` and `Inf` as requested in #1013. But that's for another PR.

### CODE REVIEW

**Comment by stefan-hoeck** [comment]
Any idea, which the racket bootstrap test fails? It says it couldn't find the network package...

**Comment by buzden** [comment]
> this PR converts zero argument toplevel lamdas to lazily evaluated, memoised constants on scheme backends

That's great! Will local constants (i.e. those `let`s and `where`s) also be memoised? I mean situations like
```idris
f : SomeType -> SomeAnotherType
f x = complexExpression arg (f arg) where
  arg : AType
  arg = someExpression
```

**Comment by stefan-hoeck** [comment]
> That's great! Will local constants (i.e. those `let`s and `where`s) also be memoised?

I'll have to check how these constructs are handled at the backends. But I agree that this would be desirable. Depending on the complexity involved with this such a change may have to go into another PR, though.

But first I have to fix that failing racket test (my racket implementation of `blodwen-lazy` is faulty...)

**Comment by stefan-hoeck** [comment]
So, I performed some experiments with memoizing lazy values and values bound in a `let` or `where` block. I'm using the following [branch](https://github.com/stefan-hoeck/Idris2/tree/memo_lazy) for this.

In the following  example, `n1`, `n2` and `n3` in `calc` are lazily evaluated and memoized. The generated Javascrip is listed below (the generated scheme behaves identically but is less pretty :-) )

```idris
import Debug.Trace

calc : Nat -> Nat
calc n0 =
  let n1  = delay $ (trace "foo" $ n0 + n0)
      n2  = delay $ (trace "bar" $ n1 + n1) 
      n3  = delay $ (trace "baz" $ n2 + n2)
   in n2 + n2

main : IO ()
main = do printLn (calc 1)
```

```javascript
function Main_calc($0) {
 const $1 = Debug_Trace_trace('foo', Prelude_Types_x2b_Num_Nat($0, $0));
 const $8 = Debug_Trace_trace('bar', Prelude_Types_x2b_Num_Nat($1, $1));
 return Prelude_Types_x2b_Num_Nat($8, $8);
}
```

As expected, "foo" and "bar" are printed only once when running this on chez or node. "baz" is not printed at all.

However, if I make the following change to the code (which is the same as introducing a `where` block), `n1`, `n2`, and `n3` are introduced as new toplevel functions and are no longer memoized:

```idris
import Debug.Trace

calc : Nat -> Nat
calc n0 =
  let n1 : Nat
      n1  = delay $ (trace "foo" $ n0 + n0)

      n2 : Nat
      n2  = delay $ (trace "bar" $ n1 + n1)

      n3 : Nat
      n3  = delay $ (trace "baz" $ n2 + n2)
   in n2 + n2

main : IO ()
main = do printLn (calc 1)
```

```javascript
function Main_n__2429_385_n2($0) {
 return Debug_Trace_trace('bar', Prelude_Types_x2b_Num_Nat(Main_n__2429_384_n1($0), Main_n__2429_384_n1($0)));
}

function Main_n__2429_384_n1($0) {
 return Debug_Trace_trace('foo', Prelude_Types_x2b_Num_Nat($0, $0));
}

function Main_calc($0) {
 return Prelude_Types_x2b_Num_Nat(Main_n__2429_385_n2($0), Main_n__2429_385_n2($0));
}
```

These are of course no longer memoized, and "foo" is printed four times. So, we need to prevent Idris2 from introducing toplevel functions for zero-argument functions in `where` blocks, and we'll get memoization for free. Whether these constants will then be eagerly evaluated or not depends on whether we wrap them in a `Lazy` or not (which I'm not sure is working properly when I look at the generated Javascript above...)

**Comment by Z-snails** [comment]
I'm happy to merge this now, unless you want to experiment some more with lazily evaluating `let` and `where`?

Although I think that feature would be better as a separate PR.

**Pull request merged**
