### PR TITLE
Use clang-format

### PR DESCRIPTION
**Pull request by stepancheg**
* Add `.clang-format` with some meaningful values
* There's no single style in C code, so any options will cause reformatting
* Run it

`clang-format` seems to be not supported by super-linter out of the
box, so the correctness of the style won't be checked.

One possible option is to add
[clang-format lint action](https://github.com/marketplace/actions/clang-format-lint).

### CODE REVIEW

**Comment by gallais** [comment]
I'd rather we adopt a style that's enforced by the CI. Otherwise it
probably won't be respected. Does super linter provide a C linter?
This way we wouldn't have to rely on yet another linting action.

**Comment by stepancheg** [comment]
Super-linter does not support clang-format.

I have created feature requests:
* in super-linter https://github.com/github/super-linter/issues/1744
* in cpplint (which is used by super-linter) https://github.com/cpplint/cpplint/issues/180

**Comment by stepancheg** [comment]
`clang-format` support committed to `super-linter`. But it would take a couple days until they release it.

**Comment by mattpolzin** [comment]
Looks like clang linting support landed in version 4.5 of super-linter! The version used by Idris is currently 3 so that value will need to be bumped in the .github/workflows file for the linting workflow.

**Comment by gallais** [comment]
I'll close this one given the massive conflicts.

**Pull request closed without merging**
