### PR TITLE
[ fix ] issue 2537

### PR DESCRIPTION
**Pull request by stefan-hoeck**
So, I tried fixing #2537, and it actually seems to work (see the new test), but I get three other test failures I'm not sure how to deal with. Pinging @Z-snails , because we've discussed this on discord.

### CODE REVIEW

**Comment by Z-snails** [comment]
codegen/builtin001 appears to be equivalent. I can have a look at the vmcode interpreter if you'd like, although I don't remember it at all :rofl:. The other one appears to be a reordering of garbage collection stuff, so maybe that's ok

**Comment by stefan-hoeck** [comment]
> codegen/builtin001 appears to be equivalent. I can have a look at the vmcode interpreter if you'd like, although I don't remember it at all rofl. The other one appears to be a reordering of garbage collection stuff, so maybe that's ok

Thanks for the quick reply. So I guess I can just take the new output for `codegen/builtin001`, yes? I'd be glad if you could have a look at the vmcode stuff.

Now, whom should I ping about the C garbage collection test?

**Comment by locriacyber** [comment]
I think this is ok to merge?

**Comment by Z-snails** [comment]
I don't think garbage collection order is important/should be relied on, so if you're ok with it, I'd be fine merging this if the expected output of the failing test is changed

**Comment by stefan-hoeck** [comment]
> I don't think garbage collection order is important/should be relied on, so if you're ok with it, I'd be fine merging this if the expected output of the failing test is changed

I don't know enough about GC to comment on this, but it would be great if we could get to merge it. Should I adjust the remaining test output?

**Comment by gallais** [comment]
What @Z-snails says makes sense to me.
Let's ping @madman-bob just in case.

**Comment by stefan-hoeck** [comment]
I adjusted the last test output. This should be ready now. Thanks all for your help!

**Pull request merged**
