### PR TITLE
[RefC] [Cleanup] Pattern matching generates simpler code.

### PR DESCRIPTION
**Pull request by seagull-kamome**
# Description

The jump tables generated by pattern matching seem completely unnecessary. A simpler conditional branch code would reduce malloc/free costs. It also seems to me that debugging would be easier.

## Should this change go in the CHANGELOG?

- [X] If this is a fix, user-facing change, a compiler change, or a new paper
      implementation, I have updated [`CHANGELOG_NEXT.md`](https://github.com/idris-lang/Idris2/blob/main/CHANGELOG_NEXT.md) (and potentially also
      `CONTRIBUTORS.md`).

### CODE REVIEW

**Comment by seagull-kamome** [comment]
I am thinking of eliminating special constructors as my next plan, and this PR is in preparation for that.

**Comment by andrevidela** [comment]
Anything that deletes looks good to me, any objectsion?

**Comment by mattpolzin** [comment]
> any objections

only that I know dependent types make case statements deceivingly tricky so (without knowing whether this is a valid concern) I wonder if there are certain dependent case patterns that aren’t fully covered by test cases that would stop working. 

On the plus side, there are already certain limitations with the RefC backend so I’m not totally opposed to merging and keeping this in mind if anyone reports new problems that sound like they could be related to this change.

**Comment by seagull-kamome** [comment]
I added a test in the previous commit.
This test should be placed in allbackends, but for now it is in tests/refc because of the issues in Issue #3161 and #3158.

**Comment by andrevidela** [comment]
I think we're good to go here then

**Pull request merged**
