### PR TITLE
A bit of refactoring of argument elaboration order

### LINKED ISSUE #1743: Irrefutable pattern in `let` binding in a type declaration stops patterns from accessing implicit arguments in its scope
# Steps to Reproduce
```idris
works : (n : (Nat, Nat)) -> let mk = n in {y : Bool} -> (z : Bool) -> String
works (m, k) {y} z = ?h1

fails : (n : (Nat, Nat)) -> let (m, k) = n in {y : Bool} -> (z : Bool) -> String
fails (m, k) {y} z = ?h2
```
# Expected Behavior
Both should type-check fine.

# Observed Behavior
Only the first definition type-checks, the second one fails with:
```
 line 5 col 0:
     While processing left hand side of fails. y is not a valid argument in fails ?n ?z.
     
     Foo:5:1--5:19
      1 | works : (n : (Nat, Nat)) -> {y : Bool} -> (z : Bool) -> String
      2 | works (m, k) {y} z = ?h1
      3 | 
      4 | fails : (n : (Nat, Nat)) -> let (m, k) = n in {y : Bool} -> (z : Bool) -> String
      5 | fails (m, k) {y} z = ?h2
          ^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by edwinb**
In theory argument elaboration order doesn't matter, but in practice we
sometimes make choices for performance reasons, like helping with
disambiguation by knowing the target type.

This was kind of messy, now we can more clearly see what's going on.
Also, more importantly, it gives us a bit more control which we
sometimes need. For example, if we go choose to go right to left for
some performance heuristic it might turn out we don't have enough
information yet, in which case we need to delay and try again later.

Fixes #1743

### CODE REVIEW

**Comment by gallais** [comment]
If you have the executable lying around, what's the impact of this PR on #1012?

**Comment by edwinb** [comment]
> If you have the executable lying around, what's the impact of this PR on #1012?

It didn't make any difference, but I'll see if the changes I've made make it any easier to find out what's going on with it.

Not sure what's up with CI here. I'll investigate.

**Comment by edwinb** [comment]
Ah, right, it wouldn't help #1012 because it's only a particular case where it's willing to delay at the moment. Maybe there's a way to get a bit more control though. I'll take a look while I'm still thinking about it.

**Comment by gallais** [comment]
> Not sure what's up with CI here. I'll investigate.

It's not specific to your PR: ubuntu-self-host-racket has been hanging since
[this unrelated commit](https://github.com/idris-lang/Idris2/commit/ada33b90a1b026cfef8e924456a507f030a3446a) where github killed the job after 6h
stuck on VMCode.

**Comment by edwinb** [comment]
Well that is mystifying. I'm going to hope it's a temporary glitch, then, but I suppose I could check if it's reproducible locally just in case.

**Pull request merged**
