### PR TITLE
[prelude] Add explicit constructor to every interface

### PR DESCRIPTION
**Pull request by Russoul**
As was shown in #1382 Idris has a hard time figuring out interface constraints in particular cases. The problem is exacerbated when you want another interface to depend on an interface like in #1382 - it appears that this simply can't be accomplished at the moment. 
Because Idris won't be able to tell that the sub-interface constraint is satisfied. Even `using` doesn't make any difference. 

The only solution I am aware of is to explicitly pass the instance of the parent interface to the sub-interface constructor.

This PR exposes constructor of every interface in Prelude.

### CODE REVIEW

**Comment by stefan-hoeck** [comment]
Wow, I didn't even know one could do that (giving explicit constructors to interfaces, I mean). Is this documented somewhere? Otherwise I think it should be.

**Comment by Russoul** [comment]
Yeah, it's one of those hidden features of Idris. Almost sure it isn't documented anywhere.

**Comment by andrevidela** [comment]
Could we document it somewhere while we're at it? maybe here? https://github.com/idris-lang/Idris2/blob/master/docs/source/tutorial/interfaces.rst

**Comment by andrevidela** [comment]
Looks good to me!

**Pull request merged**
