### PR TITLE
Some TTC loading improvements

### PR DESCRIPTION
**Pull request by edwinb**
Fix one situation where ttcs were reloaded unnecessarily, and do a bit more metavariable inlining so there's fewer definitions we need to save out. Overall this took about 8s off building Idris, for me.

### CODE REVIEW

**Comment by edwinb** [comment]
This is odd - I guess I should rebuild libraries and test this from scratch. I'll poke further. I have more things I want to do in this PR anyway so I've set it to draft for now.

**Comment by edwinb** [comment]
Oh, I think that error is something else - it's because the inlining exposes names that probably should have been imported since they're referred to in the completely explicit definition.

**Comment by gallais** [comment]
> it's because the inlining exposes names that probably should have
  been imported since they're referred to in the completely explicit
  definition.

Yeah I did not mean internal names, I meant out of scope names.
But they're only out of scope in userland IMO: the file itself
transitively depends on the right modules so these names should
be visible to the compiler when filling in implicit arguments.

That's the source of the error we have in #845 and also I suspect in #1086.

**Comment by edwinb** [comment]
Aha, yes, that's a good point. So this PR just exposes another instance of that. Not sure how to resolve it to be honest, but I'll come back to it.

**Comment by edwinb** [comment]
Hmm, this is awkward. On the name problem, the error happens during linearity checking, and we need the type of the missing name to do that successfully. So this (and therefore #845) won't be as easy to resolve as I'd hoped. For this particular PR, I'm just putting the required import in, but the undefined name problem needs a bit more thought.

**Pull request merged**
