### PR TITLE
Add popen and pclose from Idris 1

### PR DESCRIPTION
**Pull request by timsueberkrueb**
Mostly copied from Idris 1. I have only tested it on Ubuntu though.
Is this the right place for the test case?

### CODE REVIEW

**Comment by edwinb** [comment]
Yes, that's right for the test case, thanks for porting, and sorry to be slow to comment. In looks like the CI needs a poke though.

**Comment by melted** [comment]
It's using the old CI setup, it would be best if this was rebased on master before merging.

**Comment by timsueberkrueb** [comment]
The test case fails on Windows but unfortunately without any error output after "opened".

**Comment by melted** [comment]
It says "No entry for pclose" quite a bit higher up in the output, guess that went to stderr. I can try to run it later after work.

**Comment by melted** [comment]
It's _pclose on windows, probably best to just put in an idris2_pclose: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/pclose?view=vs-2019

But in the long run it would be nice if we could put such differences in the %foreign in some way.

**Comment by melted** [comment]
I tried to put an if statement in one of those %foreign functions, but the compiler didn't buy it :-)

**Comment by melted** [comment]
Another problem, I'm looking at it now.

**Comment by timsueberkrueb** [comment]
Thank you @melted. Looks like Windows is happy now.

**Comment by timsueberkrueb** [comment]
There's probably a better way to write this test case, though.

**Comment by melted** [comment]
Guess you could have put an if in `run` instead and used cygpath to get a windows path, but this is fine.

**Pull request merged**
