### PR TITLE
[ fix ] Memoize intermediary results in JS backends

### PR DESCRIPTION
**Pull request by stefan-hoeck**
See [discord](https://discord.com/channels/827106007712661524/841274390481600562/849316249677725816) for context.

### CODE REVIEW

**Comment by gallais** [comment]
Can we add a `perf` test case to `node/` that only passes in a reasonable amount
of time if we don't break this?

**Comment by stefan-hoeck** [comment]
> Can we add a `perf` test case to `node/` that only passes in a reasonable amount
> of time if we don't break this?

Just a quick question: In such a test, do we use some kind of timeout to prevent the test from running forever?

**Comment by gallais** [comment]
Nope, cf. the `tests/idris2/perfX` tests

**Comment by stefan-hoeck** [comment]
This should be ready now.

**Pull request merged**
