### PR TITLE
Add Homebrew installation instructions

### LINKED ISSUE #317: Mention Homebrew formula as alternative installation method
Usually, I would just do a PR adding those few lines of markdown but I'm unsure where do you want to place them 🤔 
If anyone can point me in the right direction I'll gladly update docs myself or someone else can do that if they like. It is distributed under `idris2` moniker: https://formulae.brew.sh/formula/idris2#default 🎉

### PR DESCRIPTION
**Pull request by vladimyr**
This adds Homebrew installation instructions to `INSTALL.md` and Getting Started guide.
Closes #317

### CODE REVIEW

**Comment by vladimyr** [comment]
Note that Homebrew distribution does not require `bash` nor `realpath` and instead links directly to compiled chez script with the following hashbang: `#!/usr/local/opt/chezscheme/bin/chez --script` ⚠️

**Comment by melted** [comment]
Thanks!

Nice as installing from brew is, I don't think we should lead off with an installation method that not everybody can use and doesn't give them a fresh install from git. I propose that you split that first section into "installing from source" and "installing from a package manager" and move the brew stuff to the later one. Then hopefully we can add more to that later.

**Comment by melted** [comment]
You can also make links to the sections and put on top so people can just jump to the one they're interested in.

**Comment by vladimyr** [comment]
@melted I mostly did it because looking through my own eyes I just want to find quickest possible way to install and be done with it so I can focus on more fun stuff. But that is pretty much addressed with your other comment suggesting to implement clickable goto-s. That surely sounds like a better option, so I'll update PR accordingly.

> Nice as installing from brew is, I don't think we should lead off with an installation method that not everybody can use and doesn't give them a fresh install from git.

FWIW you can get the latest version directly from git using brew and compile it on your own machine:
```
brew install --HEAD idris2
```

**Comment by vladimyr** [comment]
@melted I updated PR as you suggested. Does it look ok now?

**Comment by melted** [comment]
Sure!

**Pull request merged**
