### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by melted**
213 of 218 tests passes, which is pretty good for now.

This needs a new bootstrap image to run to the end. But one can just pick the one from `build/exec` on the first run and copy it to the bootstrap folder. So I don't add that noise to this commit.

### CODE REVIEW

**Comment by melted** [comment]
It's somewhat hacky, there's a new bootstrap-win.sh, when an if statement would have done.

**Comment by melted** [comment]
Next step is to get some CI up and running. Maybe it's time to try out Github Actions?

**Comment by gallais** [comment]
> Maybe it's time to try out Github Actions?

FYI travis also has windows support and that includes msys2 which seems like
a popular solution to build idris2 if I'm to believe the slack channel
https://docs.travis-ci.com/user/reference/windows/#how-do-i-use-msys2

**Comment by ziman** [comment]
FWIW, we use Travis to build Windows binaries for another project and it works well.

**Comment by edwinb** [comment]
Great, thank you! I wonder if this will work on Travis - I would like to keep the windows build working.

**Pull request merged**
