### PR TITLE
fix 2279

### PR DESCRIPTION
**Pull request by jfoutz**
builds and self hosts locally, with racket 8.3, but is dangerous for 2 reasons.
I'm not really set up to compare behavior against 8.2 but I _believe_ this will break bootstrapping with 8.2. 

There are failing tests. I forked from main rather than the release, so I don't know if that's expected or a side effect of this change. (although quite a few look totally unrelated to floating point numbers, those that do reference floats are scary).

but I don't think this
```
index 4482a376..e69de29b 100644
--- a/idris2/basic068/expected
+++ b/idris2/basic068/output
@@ -1,2 +0,0 @@
[B [A 5]]
{B {A 6}}
Golden value differs from actual value.
```
could be related.

Also, it sure seems like `bootstrap/idris2_app/idris2.rkt` is auto generated, so perhaps this is a pointless pr.

### CODE REVIEW

**Comment by jfoutz** [comment]
Since the tests passed, this seems pretty safe. This just corrects the path for the float functions in racket 8.3. I do not know, but I suspect the ubuntu path was disabled, because it couldn't bootstrap.And (I'm still guessing here) ubuntu has the latest racket. Without this change (or something like it), you can't bootstrap with the current release of racket.

**Comment by attila-lendvai** [comment]
whatever needs to be fixed, it needs to be done in the compiler.

the files you have changed are compiler generated files comitted into the git repo as _bootstrap shortcuts_, i.e. to speed up bootstrapping the Idris compiler.

please open an issue that describes the problem, preferably with some copy-pasted output in its description, and/or describing what needs to be changed in the output, and this PR should probably be closed (once the opened issue has been cross-referenced in the comments).

**Comment by attila-lendvai** [comment]
scratch that, i see that you have already created an issue for this: https://github.com/idris-lang/Idris2/issues/2279

**Comment by jfoutz** [comment]
Yeah, you're right. https://github.com/idris-lang/Idris2/pull/2286

**Pull request closed without merging**
