### PR TITLE
Add 'make clean' before 'make install-api'

### PR DESCRIPTION
**Pull request by avalonx**
'make clean' is a needed step before doing 'make install-api'
https://github.com/idris-lang/Idris2/issues/1493

### CODE REVIEW

**Comment by gallais** [comment]
Isn't the case it's only needed if you build from bootstrap?

**Comment by avalonx** [comment]
Yes. I thought to put a comment behind it to explain that, but for the sake of keeping the install doc simple and uncomplicated, I felt that it doesn’t hurt to instruct to do a ‘make clean’ even in the event there is nothing to clean. For the sake of brevity and the need to make sure the build is cleaned before someone attempts ‘make install-api’ it seemed best to just leave out the note.

**Comment by technic** [comment]
Hi,
The correct order for me is described in the doc

> The API will only work if you've completed the self-hosting step, step 4,

So actually after `make clean` you need to do `make all && make install` again, and then `make install-api`
I also had same issue today, that I didn't look at the docs carefully. I suggest that we add the following sentence in the begining of the step 4:

This step requires that you have completed step 4. Then you should type `make install-api`

Because this postfix precondition format is really causing troubles since I assume most people just copy paste and execute commands as soon as they see them.

**Comment by avalonx** [comment]
That doesn’t work for me… ‘make install’ without first doing ‘make bootstrap SCHEME=chez’ (or ‘make bootstrap-racket’) will fail. And whenever you do ‘make clean’, you have to do the bootstrap again before you can do ‘make install’. 

However, the ‘make install-api’ does not need the bootstrap and in fact will not work if the build is not cleaned (such as happens after doing the bootstrap and ‘make install’)

Hence why I feel the install doc needs to be amended to state that a ‘make clean’ should come before ‘make install-api’ to avoid a failing  api installation.

**Comment by technic** [comment]
@avalonx this does not make sense to me, why should one bootstrap twice? 
For me in the completely fresh system the order is the following

1) Here put correct `scheme` interpreter
```
make bootstrap SCHEME=scheme
make install
```

2) Make idris2 available in the path, i.e.
```
ln -s ~/.idris2/bin/idris2 ~/bin/idris2
```

3) Clean and rebuild as in step 4
```
make clean
make
make install
make install-api
```

**Comment by edwinb** [comment]
I don't think this is necessary, as others have said, and I'd rather not include a step that isn't necessary, without explaining it, or without understanding what's actually going on. If there is something going wrong that we're not understanding, maybe it'd be better to open an issue and we'll try to work it out?

**Pull request closed without merging**
