### PR TITLE
Ignore `UseSide` annotation in non-linear as-patterns

### PR DESCRIPTION
**Pull request by mjustus**
This should hopefully unblock PR #2977.

### CODE REVIEW

**Comment by AlgebraicWolf** [comment]
It looks like it not just unblocks my PR, but also fixes #490 along the way : )

**Comment by AlgebraicWolf** [comment]
As far as I understand, this PR does not affect the way `@`-pattern works on linear arguments, only behaviour of non-linear ones is changed

**Comment by buzden** [comment]
We definitely need to add both now working test for #490 and tests that linear arguments with `@`-pattern behave correctly (i.e., that we can't reuse matched linear parts) if we don't have them already.

**Comment by mjustus** [comment]
> We definitely need to add both now working test for #490 [...]

The example provided by @donovancrichton in #490 is almost identical to the test that I provide: both use an unrestricted pattern variable bound on the RHS of an as-pattern that also happens to appear in an erased position elsewhere in the LHS of the same clause. But it also uses implicit arguments which obscure the binding site of the variable in question.

> [...] and tests that linear arguments with `@`-pattern behave correctly (i.e., that we can't reuse matched linear parts) if we don't have them already.

We already have a [test for that](https://github.com/idris-lang/Idris2/blob/04c5531d9bf95f2a02cb4d74b6594390d565b6b9/tests/idris2/linear009/qtt.idr)!

**Review by gallais — APPROVED** [review]

**Pull request merged**
