### PR TITLE
Rename some file/dir manipulation functions for consistency

### PR DESCRIPTION
**Pull request by ska80**
Renamed:

fileRemove -> removeFile

dirOpen -> openDir
dirClose -> closeDir
rmDir -> removeDir

These changes follow the same naming conventions, like createDir, changeDir, readFile etc.

This change breaks building self-hosted Idris2-in-Idris2 with Idris2-in-Idris1 but bootstrapping with generated scheme code works.

### CODE REVIEW

**Comment by edwinb** [comment]
Consistency is good, thanks - these names are left over from Idris 1, where I obviously didn't put much thought into them. I won't merge quite yet, though, because I think the change should also be made in https://github.com/edwinb/Idris2-boot so as not to break that bootstrap path. I'll do that when I get around to it...

**Comment by edwinb** [comment]
Oh dear, I was just about to merge this, but I see there's a problem with the bootstrap files, and it's more annoying than I thought to resolve. Would you mind updating them please, then I'll merge and fix idris2-boot while I'm at it.

**Comment by ska80** [comment]
@edwinb it is done

> Oh dear, I was just about to merge this, but I see there's a problem with the bootstrap files, and it's more annoying than I thought to resolve. Would you mind updating them please, then I'll merge and fix idris2-boot while I'm at it.

It is done

**Comment by edwinb** [comment]
Thanks! I'll sort out Idris2-boot soon, unless someone beats me to it

**Pull request merged**
