### PR TITLE
Put chez executable in quotes on windows, part of #1244

### PR DESCRIPTION
**Pull request by TDecki**
A proper fix will need to update the bootstrap files, but the main issue should be otherwise resolved.

### CODE REVIEW

**Comment by benhormann** [comment]
Looks like `raco` and `gsc` also need quoted. I'd inline `quoted_node` (remove the comment) from [src/Compiler/ES/Node.idr](https://github.com/idris-lang/Idris2/blob/abd5432885331390cfde74e944091e677dd4b128/src/Compiler/ES/Node.idr#L52), to match your change.

Wrapping every system command in quotes is not really a good idea?
Say you type `:sh "echo test.cmd"` at the REPL; this should mean `"echo" "test.cmd"`, but you're changing it to mean `"echo test.cmd"` (which appears to do different things depending on the existence of file "echo test.cmd").

**Comment by TDecki** [comment]
The remaing compilers are now quoted too.

As for the quotes inside the `system` function, I'm doing it because of [this](https://superuser.com/questions/238810/problem-with-quotes-around-file-names-in-windows-command-shell).

I'd gladly leave `system` untouched, it's just that at the time of writing, I did not have a idea.

**Comment by benhormann** [comment]
Windows... So do we add `systemRaw` that doesn't wrap (for [src/Idris/REPL.idr#L919](https://github.com/idris-lang/Idris2/blob/ec1e7c0db6b9ddace9b70bdaded87078163b9048/src/Idris/REPL.idr#L919))?

There's more quoting to be done for racket:
- See `findRacoExe`, the `exe` arg needs moved (then rename to `findRaco`).
- Script templates [src/Compiler/Scheme/Racket.idr#L441-L446](https://github.com/idris-lang/Idris2/blob/ec1e7c0db6b9ddace9b70bdaded87078163b9048/src/Compiler/Scheme/Racket.idr#L441-L446)

Haven't tested Gambit, but wouldn't /usr/bin/env need removed?

---

Thinking aloud, is anyone using `CHEZ="\"some path\" some args"`?
(Like how there's `IDRIS2_BOOT='idris2 --codegen racket'` in [INSTALL.md](https://github.com/idris-lang/Idris2/blob/master/INSTALL.md#4-optional-self-hosting-step)).

**Comment by benhormann** [comment]
> [cmd | Microsoft Docs](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/cmd#remarks)
> If the first character is an opening quotation mark, it is stripped along with the closing quotation mark. Any text following the closing quotation marks is preserved.

So we should wrap if the command starts with a quote.
It's even less likely to trip anyone up. It's more like CMD's prompt too.

Thinking longer term, an alternative is to consider switching these commands to `_spawnvp` / `posix_spawnp`.

**Comment by benhormann** [comment]
@TDecki Could prepend `;` instead of adding quotes.
```idris
system cmd = primIO $ prim__system $ if isWindows then ";" ++ cmd else cmd
```

Unlike sh, `;` is a parameter separator. Could choose `,` or `=` instead, but we are using it like `:;` in sh.
It's basically a space that doesn't get trimmed. Ref: https://ss64.com/nt/syntax-esc.html#delimiters

---

> Thinking longer term, an alternative is to consider switching these commands to _spawnvp / posix_spawnp.

Turns out _spawn isn't much help: [Docs | Everyone quotes command line arguments the wrong way
](https://docs.microsoft.com/en-gb/archive/blogs/twistylittlepassagesallalike/everyone-quotes-command-line-arguments-the-wrong-way#the-c-runtime-library-is-useless)

**Comment by TDecki** [comment]
Thanks for the info.

As a replacement for `system`, do the scheme implementations allow calls to `execve`/`CreateProcessW` ?

**Comment by benhormann** [comment]
Calls to `system` go through FFI (to C or scheme). It could be added as a new primitive to support/c/idris_support.c and base lib. Racket has `system*` but the Chez guide says the system module has "[various undocumented system bindings](https://cisco.github.io/ChezScheme/csug9.5/syntax.html#./syntax:s35)".

> **execve()** does not return on success, and the text, data, bss, and stack of the calling process are overwritten by that of the program loaded.

So it'd probably be `posix_spawnp`. There are all sorts of win32 calls in libidris2_support, so should be OK to add CreateProcess.
Could be good for performance too, e.g. [e0e8403](https://github.com/idris-lang/Idris2/commit/e0e8403317a16f818bbfd15ba415a1f02863c8ca) calls system a lot.

**Comment by benhormann** [comment]
```
++<<<<<<< HEAD
 +         path <- pathLookup ["chez", "chezscheme9.5", "scheme"]
 +         pure $ fromMaybe "scheme" path
++=======
+          path <- pathLookup ["chez", "chezscheme", "chezscheme9.5", "scheme"]
+          pure $ fromMaybe "/usr/bin/env scheme" path
++>>>>>>> upstream/master
```
Can drop my change to remove this conflict, makes no real difference.

Although it would probably be better to abort or emit a warning if pathLookup fails. @gallais ?
It should also do a path lookup if `CHEZ` is only a name. An absolute path is required for the bang in `schHeader`.

I missed `compileChezLibraries`, `compileChezLibrary` & `compileChezProgram` in ChezSep. @TDecki It might be better to wait until #1567 is merged, then rebase.

**Comment by edwinb** [comment]
This looks like it's gone stale, and I'm not sure what it's fixing - also there's some conflicts introduced, as well as a do-not-merge flag. So, I'm going to close it for now, but if there is an issue that it's solving please feel free to reopen (as long as it's a proper fix!)

**Comment by melted** [comment]
This should be reopened. There are trouble with spaces in paths. I think I would prefer to do the quoting in pathLookup, once and for all. As long as were using system it has to be done.

Well, it looks like it can't be reopened due to the branch renaming.

**Comment by benhormann** [comment]
There will be a lot of conflicts now.
_I added the windows fixes here, but ended up merging them via another PR instead._

Better to start a new one with the good bits.
Note that `/usr/bin/env` is a bad fallback (e.g. breaks Chez's shebang). It ought to be fatal when compiler lookup fails.

Could even simplify things by not adding a shebang...
It isn't really needed, since Chez's path can be added to the launcher script. Also easier to edit later.
Maybe there's a reason / preference to keep it?

**Pull request closed without merging**
