### PR TITLE
[ install, docs ] Add a new makefile target to install libdocs

### PR DESCRIPTION
**Pull request by ska80**

### CODE REVIEW

**Comment by gallais** [comment]
Nice. I guess it would be nice to have an `idris2 --open-docs base` cli option
to open these up without having to hunt down the location of `index.html`.
Is there something akin to `$EDITOR` for the user-chosen default web browser?

**Comment by buzden** [comment]
> Is there something akin to `$EDITOR` for the user-chosen default web browser?

Once you have an XDG-compatible system, you have `xdg-open` for this.

**Comment by ska80** [comment]
> > Is there something akin to `$EDITOR` for the user-chosen default web browser?
> 
> Once you have an XDG-compatible system, you have `xdg-open` for this.

+1

And on macOS you can just ``open `idris2 --libdir`/docs/base/index.html``

**Comment by gallais** [comment]
Ok, no need for it then.

**Pull request merged**
