### PR TITLE
feat(#3400): generate only es6

### PR DESCRIPTION
**Pull request by srghma**
# Description

but the solution is not good, it just copies the first `./support/javascript` and `./support/node` folders from a DATA_PATH (?), this will be a problem 

## Should this change go in the CHANGELOG?

- [ ] If this is a fix, user-facing change, a compiler change, or a new paper
      implementation, I have updated [`CHANGELOG_NEXT.md`](https://github.com/idris-lang/Idris2/blob/main/CHANGELOG_NEXT.md) (and potentially also
      `CONTRIBUTORS.md`).

### CODE REVIEW

**Comment by buzden** [comment]
Your PR contains a lot of unrelated changes, including some refactoring (and fix?) of building files, some code refactoring, changes in the way javascript-related foreign functions are declared, and changes in the code generation, plus maybe something I didn't get.

Some of taken decisions (e.g. changes in what's written in `%foreign`, and some renamings) should be justified, I think, and definitely can be discussed. I think, this big PR should be split to smaller ones containing only one type of changes.

**Comment by srghma** [comment]
@buzden russian, how much ukranian children raped Your father? is he on war? do You like putin? what have You done to help to overthrow him?

**Comment by andrevidela** [comment]
@srghma we all understand your pain and the catastrophe of the situation but a GitHub PR is not the place for this. We all want the unjustified conflict and violence to stop, including @buzden I'm sure.

**Comment by ownerminrazer** [comment]
> @buzden russian, how much ukranian children raped Your father? is he on war? do You like putin? what have You done to help to overthrow him?

sosal?

**Comment by srghma** [comment]
@ownerminrazer how humans appeared in the universe and what is a meaning of your life? I invite you to talk with me in a Google call and make a video for YouTube if You are not scared (srghma@gmail.com)

______

@andrevidela 

> violence to stop

Unfortunately, that's not everything. Just like some maniacs kill people because they "feel regret for butterflies inside of victims or whatever". Same Russians tell "violence should stop... When Ukraine is part of Russia" (just like my strayed uncle, who before worked in Ukrainian FBI)

______


Orc will never tell "I agree" to: 
1. Yes, Serhii, I believe the Russian occupants tortured  your friend. I believe that your friend also saw how Russian tank crew shot down a crowd of grandmothers that were running from falling bombs (because Russian tank crew was "scared", by order ofc). I believe Russians raped children in Bucha.
2. Yes, Serhii, Crimea should be Ukrainian, South Ossetia - Georgian. Transnistra - Moldovan. I believe that the you spoke with everyone in your city Rodynskoye in Donetsk and found that majority never wanted to be a part of Russia. I agree with Crimea is the same. Irredentism is horrible.
3. I agree that Russia has made a revolution in Ukraine in 2014 to be violent, by bribing football fans to kill peaceful protesters, specifically with a goal to later steal Crimea 
4. Yes, Serhii. Ukraine is completely innocent victim, never did and never wanted to make anything bad. And Russia is a Ted Bundy, who is in the process of playing with intestines of its new victim. And should be stopped.
5. Russia is a static society without a freedom to propose peaceful optimizations. (Deutsch). In current form Russia will never be able to give people the infinite progress, infinite life (by stopping heat death of a universe), infinite happiness. Ukraine - can. 
6. Appeasement never worked, To cure Russia from Nazism, Russia should suffer tremendous blow (even in form of peaceful breakup to many countries).
7. I will tell Your story to all my friends. I will try to participate in peaceful protests (by law, at least, if You don't incite violence - no one can arrest You). 
8.  Since [Self-defence is the only valid justification for violence.](https://x.com/DavidDeutschOxf/status/1637589931324219397) AND Putin is equal to Ted Bundy in a process of rape AND I would stop Ted Bundy including by violence THEREFORE I agree that putting Russian recruiting stations on fire AND a knock to the head of Putin is justified.

@buzden anyone who will agree with me on all those points is my brother.

**Comment by srghma** [comment]
> We’re all allies until proven otherwise

But he proved, by not replying with "yes, Crimea should return, putin should be in prison or killed, + other things above"

> “Do not attack anyone based on any aspect of personal identity”

So, basically You are saying if Ted Bundy will rape Your child and then decide to contribute to Idris together with You - You will be silent

And You will block me because I ask what he thinks about my tortured friend, act of killing a crowd that my friend have seen, children with torn up vaginas from Bucha

**Comment by angelinatarapko** [comment]
@gallais today called my brother, the father and mother of his wife are from Kurakhovo (destroyed now). They are in "filtration camp" to go to live in russia (they told they dont want to live in russia, they want to live in Kurakhovo). 

Citing my brother "some Ukrainians don't exit filtration camps. What happens with them - no one knows"

They are killed, in basements.

https://www.youtube.com/watch?v=vYqdso9Hx_8

https://www.youtube.com/watch?v=V6QklqzuTto

**Pull request closed without merging**
