### PR TITLE
Make pathToNS handle absolute path

### PR DESCRIPTION
**Pull request by andylokandy**
Based on https://github.com/idris-lang/Idris2/pull/200

This allows absolute input file in any situation.

And since System.Path is out of sync with Utils.Path, I copied the src/Utils/Path.idr to contrib.

### CODE REVIEW

**Comment by edwinb** [comment]
Ah, I see you already did the improvement, thanks!

**Comment by edwinb** [comment]
Following this, I'm now getting, in vim mode on reloading a file while working on Idris 2:

```
"ProcessDef.idr" 879L, 38437C written
Uncaught error: Error: Source file "/home/edwin/Research/Idris2/src/TTImp/ProcessDef.idr" is not in the source directory "/home/edwin/Research/Idris2/src/TTImp/src"
```

This is undoubtedly true, but I don't know why it's checking that...

**Comment by edwinb** [comment]
Here's a way to reproduce it outside vim, just load one of the Idris 2 source files with an absolute path:

```
edwin@yaffle:~/Research/Idris2/src/Idris$ idris2 /home/edwin/Research/Idris2/src/Idris/Elab/Interface.idr --find-ipkg
     ____    __     _         ___                                           
    /  _/___/ /____(_)____   |__ \                                          
    / // __  / ___/ / ___/   __/ /     Version 0.2.0-eb141cd54
  _/ // /_/ / /  / (__  )   / __/      https://www.idris-lang.org           
 /___/\__,_/_/  /_/____/   /____/      Type :? for help                     

Welcome to Idris 2.  Enjoy yourself!
Uncaught error: Error: Source file "/home/edwin/Research/Idris2/src/Idris/Elab/Interface.idr" is not in the source directory "/home/edwin/Research/Idris2/src/Idris/src"
```

It looks like it's adding an extra `src` somewhere. I'll take a quick look into it, but otherwise I'll probably have to temporarily revert since otherwise I can't edit Idris 2 interactively any more...

**Comment by edwinb** [comment]
And another data point (sorry for the flood...) - loading one of the library files with `--find-ipkg` also fails, with a different error:

```
$ idris2 --find-ipkg /home/edwin/Research/Idris2/libs/base/Data/IOArray.idr 
     ____    __     _         ___                                           
    /  _/___/ /____(_)____   |__ \                                          
    / // __  / ___/ / ___/   __/ /     Version 0.2.0-ecaa73bad
  _/ // /_/ / /  / (__  )   / __/      https://www.idris-lang.org           
 /___/\__,_/_/  /_/____/   /____/      Type :? for help                     

Welcome to Idris 2.  Enjoy yourself!
Uncaught error: INTERNAL ERROR: build/ttc/IOArray.ttc: File Read Error
```

**Comment by andylokandy** [comment]
@edwinb 🤒 Well, let me look into it.

**Comment by edwinb** [comment]
I've poked a bit, and it's only an issue with `--find-ipkg`. Also, it's perfectly fine in both cases if you happen to load it from the right location (that is, the root of the module tree).

**Comment by edwinb** [comment]
Looks like it's just that `--find-ipkg` isn't setting the working directory after changing to it, and nothing has ever used this in this way before so it didn't cause I problem. I'll make a PR.

**Comment by andylokandy** [comment]
I'm using WSL2 and it seems no problem on my machine... weird.

```
/mnt/c/Users/Andy/Documents/Code/Idris/Idris2$idris2 /mnt/c/Users/Andy/Documents/Code/Idris/Idris2/src/Idris/Elab/Interface.idr --find-ipkg
     ____    __     _         ___

    /  _/___/ /____(_)____   |__ \

    / // __  / ___/ / ___/   __/ /     Version 0.2.0-e7baf313f        
  _/ // /_/ / /  / (__  )   / __/      https://www.idris-lang.org     

 /___/\__,_/_/  /_/____/   /____/      Type :? for help


Welcome to Idris 2.  Enjoy yourself!
2/94: Building Core.Name (src/Core/Name.idr)
........
94/94: Building Idris.Elab.Interface (src/Idris/Elab/Interface.idr)
Idris.Elab.Interface> 
```

**Comment by andylokandy** [comment]
This one fails but has a different error from yours

```
/mnt/c/Users/Andy/Documents/Code/Idris/Idris2$ idris2 --find-ipkg /mnt/c/Users/Andy/Documents/Code/Idris/Idris2/libs/base/Data/IOArray.idr
     ____    __     _         ___

    /  _/___/ /____(_)____   |__ \

    / // __  / ___/ / ___/   __/ /     Version 0.2.0-e7baf313f        
  _/ // /_/ / /  / (__  )   / __/      https://www.idris-lang.org     

 /___/\__,_/_/  /_/____/   /____/      Type :? for help


Welcome to Idris 2.  Enjoy yourself!
Uncaught error: Error: Source file "/mnt/c/Users/Andy/Documents/Code/Idris/Idris2/libs/base/Data/IOArray.idr" is not in the source directory "/mnt/c/Users/Andy/Documents/Code/Idris/Idris2/src"
```

**Pull request merged**
