### PR TITLE
[ base,tests ] Reduce dependency on `contrib`

### PR DESCRIPTION
**Pull request by CodingCellist**
In an attempt to minimise the number of dependencies on `contrib` in the core of the language, tests can be run in parallel using the lower-level `fork` and `Channel`. On the one lucky run where everything worked, this also seems to be faster, possibly due to re-using threads. **However** this implementation led me to discover #1552 and as such, this should not be merged until #1552 is fixed.

### CODE REVIEW

**Comment by CodingCellist** [comment]
Just a quick note (since there's a PR review spree going on) that this is still being worked on. Currently ironing out merging with the latest `master`  : )

**Comment by gallais** [comment]
@CodingCellist This seems to be working on my machine, should we consider this ready?

**Comment by gallais** [comment]
I'm planning to merge this by the end of the week. Make yourself known if you don't think it's a good idea. :)

**Comment by CodingCellist** [comment]
@gallais Hi! Yes! Sorry! I meant to reply to this a week ago and then got distracted ^^;;

It seems to work on my machine as well, which is really neat, so I'm happy for this to be merged! I'm somewhat confused as to why it's fixed itself, but I suspect it could've been something to do with #1596...
From a bit of benchmarking on my machine, using the `chez` backend with 8 threads and `/usr/bin/time` to measure things, these changes still seems to make things slightly faster (~7 seconds faster for `make test`) and more resource efficient (I get ~480% CPU usage with `Future` vs a consistent 600% CPU usage using this branch), so I think we can just merge it  : )

**Comment by gallais** [comment]
:ship:

**Comment by benhormann** [comment]
@CodingCellist `test` still depends on `contrib` for `Control.ANSI`.

@gallais The change to test.ipkg broke my bootstrap script in #1992. Shall I add `-p contrib` or `depends = contrib`?

**Comment by gallais** [comment]
I see... We can't rely on the builds to check that these dependencies are correct because we're passing

> IDRIS2_PATH="/home/runner/work/Idris2/Idris2/libs/prelude/build/ttc:/home/runner/work/Idris2/Idris2/libs/base/build/ttc:/home/runner/work/Idris2/Idris2/libs/contrib/build/ttc:/home/runner/work/Idris2/Idris2/libs/network/build/ttc:/home/runner/work/Idris2/Idris2/libs/test/build/ttc:/home/runner/work/Idris2/Idris2/libs/linear/build/ttc"

:tired_face: 

I'd say put back the `depends = contrib` because that is the correct thing to do.

**Comment by benhormann** [comment]
> I see... We can't rely on the builds to check that these dependencies are correct because we're passing

My bootstrap script does away with that nonsense, so you'll be able to rest easy 😉 

> I'd say put back the `depends = contrib` because that is the correct thing to do.

Done.

**Pull request merged**
