### PR TITLE
Remove unused modules

### PR DESCRIPTION
**Pull request by ska80**
Should these modules be removed?  They are not used and mentioned anywhere and probably were left after experimentation.

### CODE REVIEW

**Comment by edwinb** [comment]
I think they should be removed, yes. They should probably never have been there in the first place.

**Comment by buzden** [comment]
I'm wondering why `Control.App.Network` is not affected: it seems even to not to typecheck.

**Comment by ska80** [comment]
> I'm wondering why `Control.App.Network` is not affected: it seems even not to typecheck.

I guess it is still WIP

**Comment by buzden** [comment]
> > I'm wondering why `Control.App.Network` is not affected: it seems even not to typecheck.
> 
> I guess it is still WIP

Let's see. It looks like an early experiment before the `network` library established.

**Pull request merged**
