### PR TITLE
[ performance ] use raw prim ops in IntMap

### PR DESCRIPTION
**Pull request by stefan-hoeck**
This shaves off another ~10 seconds when typechecking `idris2api.ipkg` on my system: Since `IntMap` is already hand-specialized, we might as well replace calls to `==` and `<=`, which go via an unnecessary conversion to `Bool`, by direct calls to the primops.

### CODE REVIEW

**Comment by gallais** [comment]
Shouldn't this be happening automatically through automatically declared interface transform rules? 🤨

**Comment by buzden** [comment]
You need to transform `case` expressions rather than a function. Can this be done via transform rules?

**Comment by stefan-hoeck** [comment]
Here's the relevant part of the generated code for `treeLookup` in current HEAD:

```scheme
(let ((sc1 (PreludeC-45EqOrd-u--C-61C-61_Eq_Int arg-2 e-1))) (cond ((equal? sc1 1) (box e-2)) (else '())
```

With a call to `Eq_Int` implemented as follows:

```scheme
(define PreludeC-45EqOrd-u--C-61C-61_Eq_Int
  (lambda (arg-0 arg-1)
    (let ((sc0 (or (and (= arg-0 arg-1) 1) 0)))
      (cond ((equal? sc0 0) 0)(else 1)))))
```

And here's the same part with the optimizations in this PR:

```scheme
(let ((sc1 (or (and (= arg-2 e-1) 1) 0))) (cond ((equal? sc1 0) '())(else (box e-2))))
```

**Comment by Z-snails** [comment]
would marking the `Eq Int` implementation as `%inline` also fix this?

**Comment by stefan-hoeck** [comment]
> would marking the `Eq Int` implementation as `%inline` also fix this?

It would still go via an unnecessary conversion to `Bool`. Perhaps Chez would be able to optimize that away, though.

**Comment by gallais** [comment]
I'm not saying any difference with current HEAD on

```shell
make src/IdrisPaths.idr && time idris2 --build idris2api.ipkg
```

**Comment by Z-snails** [comment]
> I'm not seeing any difference with current HEAD on
> 
> ```shell
> make src/IdrisPaths.idr && time idris2 --build idris2api.ipkg
> ```
> 
> Edit: if anything, this branch is ~10s slower?!

Did you rebase the branch? the current main has a big performance improvement this branch most likely missing

**Comment by gallais** [comment]
Yes I did merge `main` into this branch before testing

**Comment by stefan-hoeck** [comment]
> Yes I did merge `main` into this branch before testing

I just rebased onto main and will have another look on my machine. Will report back soonish.

**Comment by stefan-hoeck** [comment]
I'm getting only minor, non-significant improvements compared to current HEAD (self-hosted), so I guess this can be closed. I think, I'm going to profile this using [idris2-profiler](https://github.com/stefan-hoeck/idris2-profiler), as it might still be relevant to know, if our bool ops are as fast as they can get, but that's for another day.

**Pull request closed without merging**
