### PR TITLE
Colist Inbounds

### PR DESCRIPTION
**Pull request by reswatson**
This implements inBounds and InBounds for Colists (hopefully the correct approach to defining InBounds). Currently these exist only for Lists. I'm not sure if there is a better way to refer to 'current file' than Data.Colist .

### CODE REVIEW

**Comment by buzden** [comment]
In this PR you've added the `Colist.idr` to the root of the repository. It seems to be a mistake. Did you mean to change the `libs/base/Data/Colist.idr`?

**Comment by buzden** [comment]
By the way, your `inBounds` function definition seems to be too sophisticated. You can do simply
```idris
public export
inBounds : (k : Nat) -> (xs : Colist a) -> Dec (InBounds k xs)
inBounds k [] = No uninhabited
inBounds Z (x::xs) = Yes InFirst
inBounds (S k) (x::xs) = case inBounds k xs of
  Yes p => Yes $ InLater p
  No up => No \(InLater p) => up p
```

**Comment by buzden** [comment]
And once you want `InBounds`, you probably want to have an indexing function that uses it, something like
```idris
public export
index' : (xs : Colist a) -> (k : Nat) -> (0 _ : InBounds k xs) => a
index' (x::_) Z = x
index' (_::xs) (S k) @{InLater _} = index' xs k
```

**Comment by reswatson** [comment]
Thanks Buzden. I'll change all that.

**Comment by gallais** [comment]
No need to close this PR & then (I assume) open another one.
You can keep pushing to the same branch and that will automatically
update the PR.

**Comment by gallais** [comment]
This has a lot of unrelated changes. Seems like you messed up a merge somewhere?

**Comment by reswatson** [comment]
I'm completely new to git (except for cloning code) but I found myself having to use git push origin colist-functions -f  ... ugly stuff. If it's wrong I'll cancel this pull request and start again. Thx.

**Comment by buzden** [comment]
> I'm completely new to git (except for cloning code) but I found myself having to use git push origin colist-functions -f ... ugly stuff. If it's wrong I'll cancel this pull request and start again. Thx.

Push with force (i.e. `-f` flag) is completely okay for branches of PRs when you are using git for github and it was exactly what you were asked for.

**Pull request merged**
