### PR TITLE
Fix for Issue 74

### PR DESCRIPTION
**Pull request by redfish64**
The problem is that if the function is defined in a sub module, then the current namespace (accessed by calling getNS) differs from the function namespace, therefore it is not considered visible by TTImp.Elab.App.checkVisibleNS

Fixed by using "setAllPublic". Not sure if this is the best way to do this.

### CODE REVIEW

**Comment by fabianhjr** [comment]
Hi, your PR contains  2 unrelated commits that cancel each other out. Could you drop those two (ce2f0b7, 1514e7b) from your merge request?

**Comment by redfish64** [comment]
Ok, sorry about that. #772

**Comment by buzden** [comment]
FYI, you could do this in the same PR by just force-pushing your git branch. So, generally, there's no need to create new PR for this.

**Comment by redfish64** [comment]
I actually used a different branch in my fork because I wanted to keep that
history (I created a new branch and forked it from idris-lang/Idris2, then
cherry picked the commit). But thanks for letting me know.

Denis Buzdalov <notifications@github.com> 於 2020年11月9日 週一 17:16 寫道：

**Pull request closed without merging**
