### PR TITLE
[ base ] Indexing Vectors.

### PR DESCRIPTION
**Pull request by jfdm**
`Elem` proofs give existential quantification that a given element *is* in the list, but not where in the list it is!
Here we give a predicate that presents proof that a given index of a vector, given by a `Fin` instance, will return a certain element.

Two decidable decision procedures are presented:

1. Check that a given index points to the provided element in the presented vector.
2. Find the element at the given index in the presented vector.

Prompted by #1891.

### CODE REVIEW

**Comment by jfdm** [comment]
I am partial to the name `Index`, but I won't let that block this PR.

But more importantly, it looks like there are a few naming conventions that we might need to write down/decided upon some time some where...

**Comment by mattpolzin** [comment]
I had a similar thought to Guillaume regarding aligning these new definitions to existing ones but my thought was related to `Elem` directly. I think it would be nice if we had `Elem x xs` and `Index idx x xs` rather than the latter swapping the order of its x/xs arguments. Or even `Index x idx xs` would be a bit more similar to the `Elem` structure.

**Comment by jfdm** [comment]
The ordering is purposeful: The most commonly synthesized value in the definition should be the last parameter in the type. This plays nicely with Dependent Pair definitions.

**Comment by mattpolzin** [comment]
> The most commonly synthesized value in the definition should be the last parameter in the type. 

I admit I may have the weaker argument here. It's just unfortunate ergonomics. Users will need to remember that `List.AtIndex` and `Vect.AtIndex` swap the order of their indices around.

I just noticed `List.AtIndex` doesn't do either of the things I suggested above but it does put the index last which means x/xs are in the same order as with `Elem` so it actually does accomplish what I was picturing regarding familiarity for anyone who has used `Elem`.

**Comment by jfdm** [comment]
@mattpolzin To elaborate on the ordering of type-level parameters, which is really about eta reducing the promoted value in a dependent pair.

I wrote `AtIndex` to primarily represent the relation:

> Given a vector `xs` and a valid index `i` in `xs` then there is an `x` such that `index i xs === x`.

Here, `AtIndex` represents the relation: `index i xs === x`. 

Which is what you want to do most of the time. 

With how things go in programming, however, we can reuse `AtIndex` to represent variants of this relation.

1. Given a vector `xs` and a valid index `i` in `xs` then there is an `x` such that `index i xs === x`.
2. Given a vector `xs`, a valid index `i` in `xs`, and a value `x`, then is `x` the value at `index i xs`.
3. Given a vector `xs` and a value `x` then if `x` is in `xs` then it will be at index `i`.

My opinion is that `i` and `xs` are related through the length of the vector (encoded at the type-level) you are more than likely to have these two and then want to get the value at `i`. Thus if we order the parameters correctly we can take advantage of how Dependent Pairs are actually specified and eta reduce the `x` in the type.

That is having:

```idris
index : DecEq type => (idx : Fin n) -> (xs  : Vect n type) -> Dec (DPair type (AtIndex idx xs))
```

instead of

```idris
index : DecEq type => (idx : Fin n) -> (xs  : Vect n type) -> Dec (x ** AtIndex idx xs x)
```

Although another way is to have a custom datatype that negates the need for a dependent-pair.
Regardless of that, everyone is right ordering (nee ergonomics) *does* matter but it depends on what you want to represent primarily with the relation.

**Comment by mattpolzin** [comment]
@jfdm thanks! That explanation was great. I see your point and definitely agree you can’t optimize for all use cases all the time!

**Pull request merged**
