### PR TITLE
[ breaking ] remove parsing of dangling binders

### PR DESCRIPTION
**Pull request by gallais**
It used to be the case that

```
ID : Type -> Type
ID a = a

test : ID (a : Type) -> a -> a
test = \ a, x => x
```

and

```
head : List $ a -> Maybe a
head [] = Nothing
head (x :: _) = Just x
```

were accepted but these are now rejected because:

* `ID (a : Type) -> a -> a` is parsed as `(ID (a : Type)) -> a -> a`
* `List $ a -> Maybe a` is parsed as `List (a -> Maybe a)`

Similarly if you want to use a lambda / rewrite / let expression as
part of the last argument of an application, the use of `$` or parens
is now mandatory.

This should hopefully allow us to make progress on #1703

### CODE REVIEW

**Comment by melted** [comment]
There are a lot of weird files added in contib, like cases-25.txt

**Comment by gallais** [comment]
Given that merging master into this branch revealed two recently
introduced dangling lambdas, I should maybe hold off until the big
mergefest is over before I push this breaking change.

**Comment by ohad** [comment]
Is it possible to generate a warning first for a few weeks/1 release?

**Comment by gallais** [comment]
Shoot, I've mixed the new feature (a `Warning` constructor for the `Grammar`) with the merge.
Oh well, it'll all get squashed anyway.

**Pull request merged**
