### PR TITLE
Simplify Nix Expressions

### PR DESCRIPTION
**Pull request by fabianhjr**
This should simplify the usage of nix to be strictly about declaring dependencies and building a nix-shell for development of Idris2, removes flakes, emacs, and withPackages script.

Related to #1507

Pending: Documentation on a Docker Image and modifying dependencies

### CODE REVIEW

**Comment by guilhermehas** [comment]
Maybe, it is better to pin the <nixpkgs> channel to a specific commit. Because there is a small probability that some update of <nixpkgs> channel breaks the build.

**Comment by fabianhjr** [comment]
> Maybe, it is better to pin the Nixpkgs channel to a specific commit. Because there is a small probability that some update of the Nixpkgs channel breaks the build.

The dependencies are very stable, (gmp, clang, chez, makeWrapper) OR CI-here (idris2 itself has a "build from previous version" CI check)

The main complain has been that flakes has been flaky (experienced this myself and other contributors) and flakes is an experimental unstable feature so so far flakes has been causing more failed CI builds and many people don't know what is going on when the Nix CI fails.

The nix channel could be changed to a release channel to ensure more stability

**Comment by claymager** [comment]
I don't see how moving to a channel would provide more stability than a pinned flake.

Simplifying the nix and docker documentation is a great idea.

**Comment by fabianhjr** [comment]
Hi @claymager, thanks for your approval your idris2-nix with flakes repo is amazing. <3

Would it be ok if I do a further merge request documenting how to use idris2 on nix/nixos and send people your way?

**Comment by claymager** [comment]
A PR like this should update INSTALLING.md

**Comment by fabianhjr** [comment]
Ah that is right, I should also add some notes to contributing.

**Pull request closed without merging**
