### PR TITLE
[RefC] [Cleanup] erase ReturnStatement

### PR DESCRIPTION
**Pull request by seagull-kamome**
# Description

ReturnStatement has no role and is just noise that adds extra work.
Unless there is no other use for it, it should be removed.

### CODE REVIEW

**Comment by seagull-kamome** [comment]
2024/02/14_19:51:23 seagull@penguin:~/Projects/Idris2/tests/refc/garbageCollect
 (erase_mkrs $%=)$ LC_ALL=en_US.UTF-8 sort expected 
allocated AnyPtr freed
allocated (Ptr t) freed
2024/02/14_19:51:27 seagull@penguin:~/Projects/Idris2/tests/refc/garbageCollect
 (erase_mkrs $%=)$ LC_ALL=C sort expected 
allocated (Ptr t) freed
allocated AnyPtr freed
2024/02/14_19:51:35 seagull@penguin:~/Projects/Idris2/tests/refc/garbageCollect
 (erase_mkrs $%=)$ LC_ALL=ja_JP.UTF-8 sort expected 
allocated (Ptr t) freed
allocated AnyPtr freed

**Comment by seagull-kamome** [comment]
NOTE: I share with you that we need to pay attention to the locale when running the test.

````
2024/02/14_19:51:23 seagull@penguin:~/Projects/Idris2/tests/refc/garbageCollect
 (erase_mkrs $%=)$ LC_ALL=en_US.UTF-8 sort expected 
allocated AnyPtr freed
allocated (Ptr t) freed
2024/02/14_19:51:27 seagull@penguin:~/Projects/Idris2/tests/refc/garbageCollect
 (erase_mkrs $%=)$ LC_ALL=C sort expected 
allocated (Ptr t) freed
allocated AnyPtr freed
2024/02/14_19:51:35 seagull@penguin:~/Projects/Idris2/tests/refc/garbageCollect
 (erase_mkrs $%=)$ LC_ALL=ja_JP.UTF-8 sort expected 
allocated (Ptr t) freed
allocated AnyPtr freed
2024/02/14_19:51:44 seagull@penguin:~/Projects/Idris2/tests/refc/garbageCollect
 (erase_mkrs $%=)$ LC_ALL=en.UTF-8 sort expected 
allocated (Ptr t) freed
allocated AnyPtr freed
````

**Comment by mattpolzin** [comment]
That’s a pretty sneaky failure. This test is going to remain flaky then until we specify the locale in the `run` script right?

**Comment by seagull-kamome** [comment]
There are other tests that need the sort command. For example, the concurrency test sometimes reports false failures from timing issues (especially on my potato PC). So, I added  work around at testutils.sh.

**Review by mattpolzin — APPROVED** [review]

**Comment by seagull-kamome** [comment]
Nix trouble is difficult for me. I wish there was a better way.

**Comment by mattpolzin** [comment]
I actually think it's not so bad the way you've got it now (safesort). That said, you almost had it working when you used `$(which sort)` to find it; the missing thing was adding `which` to what Nix calls "checkInputs": https://github.com/idris-lang/Idris2/blob/main/nix/package.nix#L41

**Pull request merged**
