### PR TITLE
[ repl ] Add the ability to get detailed help, e.g. `:help :help`

### PR DESCRIPTION
**Pull request by CodingCellist**
This has been a thing that has bothered me and other users and helpers alike: REPL commands like `:set` and `:let` have subtle behaviour which is not easily discoverable. This adds the ability to actually get this info, by allowing `:help` to take a repl command as an argument. The general `:help` text (i.e. no arguments) containing the list of repl commands and their single lines of help is preserved.

### CODE REVIEW

**Comment by CodingCellist** [comment]
(this should probably be squashed and merged, since it's just a bunch of WIP commits until I finally got it working as I intended it to)

**Comment by CodingCellist** [comment]
Seems to unfortunately be suffering from #2087. I've used the same "fix" as with #2044 (which revealed the issue), but this really is an odd problem...

**Comment by CodingCellist** [comment]
CI pls... :sob:

**Comment by CodingCellist** [comment]
Dang, I was really hoping that'd work... :disappointed:

What I find super odd, is that commit [c879f41](https://github.com/idris-lang/Idris2/pull/2722/commits/c879f41684b9a743601b475bf35e155f158b2adb) fixes one of the tests but not the other. Which suggests it was never a multiline string vs `unlines` thing. But that's just even more confusing...

**Comment by CodingCellist** [comment]
At this point I'm tempted to just comment out the test honestly. This is super weird behaviour, and if I understand #2087 correctly, an issue that **only** occurs on the CI machines; no "real" machines running Nix or Windows have observed the issue afaiu.

**Comment by gallais** [comment]
I've added just enough of a feature to `Test.Golden` that we can stop running these tests on the CI
while still running them on people's machines. We'll see whether it is indeed the case that this only
manifests on CI machines.

**Comment by CodingCellist** [comment]
@gallais, that's amazing, tysm!

Am I good to merge this in that case?  : )

**Comment by gallais** [comment]
Go for it! 🚀

**Comment by gallais** [comment]
Looks like there is a bug in the `Test.Golden` implementation: CI is not running any of the tests.

**Comment by gqqnbig** [comment]
Thank you. Until I saw this, I'd never known how to use :let.

**Pull request merged**
