### PR TITLE
[ fix #1260 ] Use `blodwen-stringbytelen` instead of C's `strlen`

### LINKED ISSUE #1260: \NUL characters inside of strings lead to truncation
`\NUL` characters inside of strings are not handled correctly and sometimes
lead to truncation.

# Steps to Reproduce

Create the file `NulStrings.idr`:

```idris
import Data.Buffer

s : String
s = "string\NUL containing a NUL character"

main : IO ()
main = do
  printLn s
  printLn $ stringByteLength s
```

It is important to put the code inside a file, as REPL behaviour is slightly
different (see below).

Run:

    idris2 --exec main NulStrings.idr                                                                                                   :( 130 21-04-02 - 10:36:35

# Expected Behaviour

    "string\NUL containing a NUL character"
    34

# Observed Behaviour

    "string"
    6

## Note Regarding REPL Rehaviour

On the REPL, strings are not truncated (probably because no step to->from TTC
occurs), but the `stringByteLength` error can be verified:

    Main> :module Data.Buffer
    Imported module Data.Buffer
    Main> :exec printLn $ "abc\NULdef"
    "abc\NULdef"
    Main> :exec printLn $ stringByteLength "abc\NULdef"
    3

### PR DESCRIPTION
**Pull request by cypheon**
Use the already existing (both Chez and Racket) support function to
accurately determine the UTF-8 byte count of a string, as the C function
(unsurprisingly) stops counting at NUL characters.

Currently the only usage of `stringByteLength` is in the implementation
`TTC String`, which leads to string truncation when a string containing
NUL bytes is serialised to a .ttc file.

Test cases to verify correct handling of strings containing NUL characters are included in the commit.

This should fix #1260

### CODE REVIEW

**Comment by gallais** [comment]
I believe this is the wrong fix, cf. https://github.com/idris-lang/Idris2/issues/1260#issuecomment-814950401

**Comment by cypheon** [comment]
So the reasoning behind the change was the following:

Lets assume we have a string with `f` ASCII characters (**f**ull length), with a NUL character at position `n` (**n**ul length) with `n < f`

`Data.Buffer.prim__setString` is implemented with this Scheme support code:

https://github.com/idris-lang/Idris2/blob/c725b11c891b9f9f1e25ead66d9fc75a91b69836/support/chez/support.ss#L191-L194

That is:
1.1. The string is encoded as an UTF-8 bytevector
1.2. `f` (the full length of that bytevector) amount of bytes are copied to the buffer

`TTC String`, `toBuf` works like this:

https://github.com/idris-lang/Idris2/blob/c725b11c891b9f9f1e25ead66d9fc75a91b69836/src/Libraries/Utils/Binary.idr#L177-L185

2.1. The `stringByteLength` of the given string returns the "short" count `n` which is then stored in `req`
2.2. `n` is written to the Buffer as an Int (`toBuf b req`)
2.3. After that, the `f` UTF-8 encoded bytes are written to the Buffer (using `setString`, as described above)
2.4. The "cursor" in the TTC output is forwarded `n` bytes (`put Bin (appended req chunk)`)
(2.5. Since the cursor was only forwarded `n` bytes, but `f` bytes where written to the Buffer, the trailing `f-n` bytes will be overwritten by the next `toBuf` call)

So for me it makes sense that the number of bytes written in step 2.3. should always be consistent with the "prefix length" written in step 2.2., so that `fromBuf` will return a String equal to the one that was passed to `toBuf`, (which should be the ultimate goal for a serialization-deserialization cycle :)

This PR would change `stringByteLength` from `C:strlen` to this:

https://github.com/idris-lang/Idris2/blob/c725b11c891b9f9f1e25ead66d9fc75a91b69836/support/chez/support.ss#L188-L189

Which would guarantee, that the "length prefix" written in 2.2. is always the same as the actual number of bytes written in 2.3.

So what do you think? Did I make some sense, or am I on the wrong track? Do you think any existing code could be broken by this change?

**Comment by stepancheg** [comment]
I believe the fix is correct, and wherever we truncate string on NUL character, we need to fix it (including RefC backend BTW, which assumes all strings are NUL-terminated). The fix does not necessary have to fix everything, so this PR LGTM.

I'd also like to point that there's a significant issue with current buffer implementation in Chez: `stringByteLength` stops at NUL character, but setString puts the whole string. So using `stringByteLength` + `setString` now may result in runtime crash at best or data corruption at worst. So this PR at least makes this part consistent.

**Comment by gallais** [comment]
Okay I'll merge master into the PR then to see whether it still builds.

**Comment by cypheon** [comment]
Thanks for merging!
@stepancheg: Thanks for having a second look at this!

**Pull request merged**
