### PR TITLE
add Inspect idiom

### PR DESCRIPTION
**Pull request by clayrat**
As suggested in https://github.com/idris-lang/Idris2/issues/893

### CODE REVIEW

**Comment by gallais** [comment]
I reused the names in agda's stdlib in the original snippet but
they're maybe not the best? Here are propositions:

`Reveal f` is the the relation corresponding to the graph of `f`
so we could maybe call the record `Graph` instead?

As for `inspect`, I could see either `remember` (because that is
what we are trying to do: remember the origin of `f x`) or some
sort of `$`-like infix syntax because it is just a fancy apply.

**Comment by clayrat** [comment]
I do like `remember`! However `Graph` is IMO too overloaded. We need a more "technical" word, maybe `FnGraph` or `Section`, [as in topology](https://en.wikipedia.org/wiki/Section_(fiber_bundle))?

**Comment by gallais** [comment]
`Image` would also work as `Image f x` is the predicate that only
accepts the `y`s that are such that `f x === y`.

**Comment by clayrat** [comment]
`Image` is also a bit generic, could be confusing out of context. I'm thinking to go with `FnGraph`, wdyt?

**Comment by gallais** [comment]
If we are worried about things being confusing out of context,
we may put it in `Data.Function` and that should be unambiguous.

**Comment by clayrat** [comment]
Ok, let's go with `Data.Fun.Graph` then.

**Pull request merged**
