### PR TITLE
Use overwrite install to fix glib installation

### PR DESCRIPTION
**Pull request by andrevidela**
# Description

fix brew (for real this time)

## Should this change go in the CHANGELOG?

- [ ] If this is a fix, user-facing change, a compiler change, or a new paper
      implementation, I have updated [`CHANGELOG_NEXT.md`](https://github.com/idris-lang/Idris2/blob/main/CHANGELOG_NEXT.md) (and potentially also
      `CONTRIBUTORS.md`).

### CODE REVIEW

**Comment by andrevidela** [comment]
this fixes the `brew link` issue but now tests don't pass :|

**Comment by andrevidela** [comment]
Is it failing because there is no racket instance but only chez scheme? If that's the case I'm confused as to how it work in the first place

**Comment by mattpolzin** [comment]
It's failing the nodejs all-backend tests. I see it seems to not be printing very much of the expected output for some reason.

**Review by mattpolzin — APPROVED** [review]
I've got a good feeling about this passing CI.

**Pull request merged**
