### PR TITLE
Extract modules from Prelude

### PR DESCRIPTION
**Pull request by stepancheg**
Extract `Prelude.Basics`, `Prelude.Uninhabited` same way it is done in Idris 1.

AFAIU, we need to split `Prelude` to allow `length` overloads (#346), and this is the first part of it.

Is there a reason `Prelude` is 1800LOC single file module in Idris 2?

### CODE REVIEW

**Comment by stepancheg** [comment]
Trying to figure out how to reproduce it locally. All tests pass locally, looks like tests uses previously installed Idris, not just built.

**Comment by melted** [comment]
You probably need to update the bootstrap idris if tests are failing.

**Comment by melted** [comment]
Having the prelude in a single file helps against unbounded expansion of it, is my best guess about that.

**Comment by stepancheg** [comment]
Updated PR with the only first commit, without `Bool`, which is somewhat harder to extract.

**Comment by gallais** [comment]
Thanks!

**Comment by edwinb** [comment]
So this isn't mentioned in the Prelude, but the reason it's so gigantic at the moment is that we don't yet have a way of saying that, no matter what module things are defined in, their namespace should be `Prelude` whatever. The problem with moving things into other modules (at the moment) then, is that you can no longer disambiguate with `Prelude.flip` (or whatever).

Not that this makes splitting things out a bad idea, of course - the Prelude would definitely be better split across several files. But we should think about namespaces.

**Comment by edwinb** [comment]
Probably the way to resolve this is to finally implement `import ... as`. If we did `import public Prelude.Basics as Prelude`, and the effect was to rename everything public from `Prelude.Basics` to `Prelude`, then I think that'd solve it.

I've never got around to `import ... as` because, quite honestly, the prospect bores me... it's probably just a matter of doing the appropriate renamings after loading in `ProcessIdr.readModule`.

**Comment by stepancheg** [comment]
@edwinb probably it should be the opposite: E. g. `Nat` should be `Data.Nat.Dat`, available from `Prelude`, but to disambiguate `Data.Nat.Dat` should be used, not `Prelude.Nat` or `Prelude.Nat.Nat`.

**Comment by gallais** [comment]
> If we did import public `Prelude.Basics` as `Prelude`, and the effect was to rename everything public from `Prelude.Basics` to `Prelude`, then I think that'd solve it.

Would it still work if we were trying to re-export two distinct functions called `length`?

**Comment by stepancheg** [comment]
@gallais

> Would it still work if we were trying to re-export two distinct functions called length?

I barely know Idris, but it might work like this:
* both `length` functions are available as `length` when module (`Prelude`) is imported
* `Prelude.length` does not work
* `Data.List.length` and `Data.String.length` work

**Pull request merged**
